/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `store_sales_data` (
  `sale_data_id` int(11) NOT NULL AUTO_INCREMENT,
  `store_site_id` int(11) NOT NULL,
  `import_dt` datetime NOT NULL,
  `order_date` date NOT NULL,
  `store_order_num` varchar(100) NOT NULL,
  `dvd_num` int(11) DEFAULT NULL,
  `ext_type_name` varchar(100) DEFAULT NULL,
  `cust_email` varchar(255) NOT NULL,
  `cust_name_first` varchar(100) DEFAULT NULL,
  `cust_name_last` varchar(100) DEFAULT NULL,
  `cust_addr_1` varchar(100) DEFAULT NULL,
  `cust_addr_2` varchar(100) DEFAULT NULL,
  `cust_city` varchar(100) DEFAULT NULL,
  `cust_state` char(2) DEFAULT NULL,
  `cust_zip` varchar(10) DEFAULT NULL,
  `cust_country` char(2) DEFAULT NULL,
  `store_movie_num` int(11) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `studio` varchar(255) DEFAULT NULL,
  `cond_name` varchar(50) DEFAULT NULL,
  `quantity` int(11) DEFAULT 1,
  `price_paid` decimal(15,2) DEFAULT NULL,
  `shipping_credit` decimal(15,2) DEFAULT NULL,
  `store_fees` decimal(15,2) DEFAULT NULL,
  `total_due` decimal(15,2) DEFAULT NULL,
  `store_ship_code` char(1) DEFAULT NULL,
  `cust_verified` tinyint(1) NOT NULL DEFAULT 0,
  `movie_verified` tinyint(1) NOT NULL DEFAULT 0,
  `price_verified` tinyint(1) NOT NULL DEFAULT 0,
  `credit_verified` tinyint(1) NOT NULL DEFAULT 0,
  `total_verified` tinyint(1) NOT NULL DEFAULT 0,
  `order_verified` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`sale_data_id`),
  KEY `store_sales_data_store_site_id_IDX` (`store_site_id`) USING BTREE,
  KEY `store_sales_data_import_dt_IDX` (`import_dt`) USING BTREE,
  KEY `store_sales_data_order_verified_IDX` (`order_verified`) USING BTREE,
  KEY `store_sales_data_ext_type_name_IDX` (`ext_type_name`) USING BTREE,
  KEY `store_sales_data_cust_email_IDX` (`cust_email`) USING BTREE,
  KEY `store_sales_data_store_movie_num_IDX` (`store_movie_num`) USING BTREE,
  KEY `store_sales_data_cond_name_IDX` (`cond_name`) USING BTREE,
  KEY `store_sales_data_store_order_num_IDX` (`store_order_num`) USING BTREE,
  CONSTRAINT `store_sales_data_store_site_id_FK` FOREIGN KEY (`store_site_id`) REFERENCES `store_sites` (`store_site_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Raw sales data exported from store site, for validation against internally tracked data';
/*!40101 SET character_set_client = @saved_cs_client */;
